### ISSUE TITLE
For own data.

### ISSUE THREAD

**Issue by redhat12345** [ahirner/pytorch-retraining#1]
I have a dataset consisting of 20 classes. How can I use this code for my dataset. Thanks in advanced. 
Train-
    class1
                 1.jpg

    class2
                  1.jpg

Test-
       class1
                 1.jpg

       class2
                 1.jpg

**Comment by ahirner** [comment]
First, put all data into `root/train/_classname_/*.jpg` and `root/val/_classname_/*.jpg`. Then, specify this `root` folder in [retrain.py](https://github.com/ahirner/pytorch-retraining/blob/master/retrain.py#L63) for now. Alternatively, have a look at this [fork](https://github.com/thomasdic2000/pytorch-retraining/blob/master/retrain_benchmark_Roofs.py). It compares different resnets.
