### ISSUE TITLE
Densenet not iterable

### ISSUE THREAD

**Issue by yamcomnet** [ahirner/pytorch-retraining#3]
**Densenets are giving errors:**

Targeting densenet201 with 2 classes
------------------------------------------
Traceback (most recent call last):
  File "retrain.py", line 340, in <module>
    model_pretrained, diff = load_model_merged(name, num_classes)
TypeError: 'DenseNet' object is not iterable

**Comment by ahirner** [comment]
```
>>> from retrain import torch
>>> torch.__version__
'0.2.0_4'
>>> from retrain import load_model_merged
>>> load_model_merged('densenet201', 2)
DenseNet (
#...
```
Hi @silakanveli, I wasn't able to reproduce your error on master. Have you had success with other versions of Densenet or PyTorch?

**Comment by buaaswf** [comment]
I have reproduce the problem and I solve it by remove "diff" in this "model_pretrained, diff = load_model_merged(name, num_classes)" 
Hope it can help you

**Comment by ahirner** [comment]
Good catch, thx @buaaswf!
